-- Create role, database, and grant permissions for MDM Customer Matching
-- Must be run as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

-- Create the database
CREATE DATABASE IF NOT EXISTS MDM_CUSTOMER_MATCHING
  COMMENT = 'Master Data Management Customer Matching demo database';

-- Create dedicated role for MDM operations
CREATE ROLE IF NOT EXISTS MDM_CUSTOMER_MATCHING_ROLE
  COMMENT = 'Role for MDM Customer Matching application operations';

-- Grant database privileges to the role
GRANT USAGE ON DATABASE MDM_CUSTOMER_MATCHING TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT CREATE SCHEMA ON DATABASE MDM_CUSTOMER_MATCHING TO ROLE MDM_CUSTOMER_MATCHING_ROLE;

-- Grant schema privileges
GRANT USAGE ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT CREATE TABLE ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT CREATE VIEW ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT CREATE STAGE ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT CREATE FUNCTION ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;

-- Grant all privileges on future objects in the schema
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;

-- Grant warehouse usage (configurable via MDM_WH environment variable, defaults to COMPUTE_WH)
-- Note: If using a different warehouse, ensure it exists before running setup
GRANT USAGE ON WAREHOUSE ${MDM_WH} TO ROLE MDM_CUSTOMER_MATCHING_ROLE;

-- Grant Cortex privileges for AI/ML features
GRANT CREATE SNOWFLAKE.ML.ANOMALY_DETECTION ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;

-- Grant all privileges on schema for Cortex Search (CREATE SERVICE requires broader permissions)
GRANT ALL PRIVILEGES ON SCHEMA MDM_CUSTOMER_MATCHING.PUBLIC TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
-- Grant database role for Cortex AI functions (if available)
-- Note: These may require additional setup depending on Snowflake account configuration
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE MDM_CUSTOMER_MATCHING_ROLE;

-- Create SNOWFLAKE_INTELLIGENCE database and schema for agent (if needed)
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE
  COMMENT = 'Database for Snowflake Intelligence and Agent services';

CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS
  COMMENT = 'Schema for Cortex Agents';

-- Grant privileges on SNOWFLAKE_INTELLIGENCE for agent operations
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE MDM_CUSTOMER_MATCHING_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SERVICES IN SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE MDM_CUSTOMER_MATCHING_ROLE;

-- Grant role to SYSADMIN for hierarchical role management
GRANT ROLE MDM_CUSTOMER_MATCHING_ROLE TO ROLE SYSADMIN;

-- Note: Users with ACCOUNTADMIN or SYSADMIN can use this role.
-- To grant to a specific user, run: GRANT ROLE MDM_CUSTOMER_MATCHING_ROLE TO USER <username>;

SELECT 'Database and role setup complete. Use role MDM_CUSTOMER_MATCHING_ROLE for subsequent operations.' AS STATUS;
