-- Consolidated setup for MDM Customer Matching (V2)
-- Includes: sequence/UDF, table DDLs, full-detail/embeddings for CUSTOMER_IDENTIFIER, and Cortex Search services

USE ROLE MDM_CUSTOMER_MATCHING_ROLE;
USE DATABASE MDM_CUSTOMER_MATCHING;
USE SCHEMA PUBLIC;  -- @Snowflake Docs

-- -----------------------------------------------------------------------------
-- Sequence and UDF for CUSTOMER_BUSINESS_ID
-- -----------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS CUSTOMER_BUSINESS_ID_SEQ
  START = 1
  INCREMENT = 1
  COMMENT = 'Sequence to generate the numeric component for CUSTOMER_BUSINESS_ID';

CREATE OR REPLACE FUNCTION GENERATE_CUSTOMER_BUSINESS_ID(SEQ_VALUE NUMBER)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Generates ID as CUS + 9-digit zero-padded number + Base36 check char.'
AS
$$
  'CUS'
  || LPAD(TO_VARCHAR(SEQ_VALUE), 9, '0')
  || IFF(MOD(SEQ_VALUE, 36) < 10,
         TO_VARCHAR(MOD(SEQ_VALUE, 36)),
         CHR(55 + MOD(SEQ_VALUE, 36))
     )
$$;

-- Tables (with related post-creation updates grouped directly after each CREATE)
CREATE TABLE IF NOT EXISTS MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_ADDRESS (
  CUSTOMER_BUSINESS_ID VARCHAR,
  CUSTOMER_NAME VARCHAR,
  ADDRESS_LINE_1 VARCHAR,
  ADDRESS_LINE_2 VARCHAR,
  CITY VARCHAR,
  COUNTY VARCHAR,
  STATE VARCHAR,
  POSTAL_CODE VARCHAR,
  POSTALCODE_EXTENSION VARCHAR,
  COUNTRY VARCHAR,
  PHONE VARCHAR,
  CUSTOMER_FULL_DETAIL VARCHAR,
  CUSTOMER_FULL_DETAIL_EMBEDDING VECTOR(FLOAT, 768)
);

-- CUSTOMER_IDENTIFIER (schema only; populated by tools/processes)
CREATE TABLE IF NOT EXISTS MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_IDENTIFIER (
  IDENTIFIER_TYPE VARCHAR,
  IDENTIFIER_VALUE VARCHAR,
  CUSTOMER_BUSINESS_ID VARCHAR,
  CUSTOMER_NAME VARCHAR,
  ADDRESS_ROLE VARCHAR,
  ADDRESS_LINE_1 VARCHAR,
  ADDRESS_LINE_2 VARCHAR,
  CITY VARCHAR,
  COUNTY VARCHAR,
  STATE VARCHAR,
  POSTAL_CODE VARCHAR,
  POSTALCODE_EXTENSION VARCHAR,
  COUNTRY VARCHAR,
  PHONE VARCHAR,
  VERIFICATION_STATUS_CODE VARCHAR,
  VERIFICATION_MESSAGE VARIANT,
  ENRICHED_INDICATOR VARCHAR,
  CONFIDENCE_SCORE FLOAT,
  SEARCH_CONFIDENCE_SCORE FLOAT,
  EDIT_DISTANCE INTEGER,
  CUSTOMER_FULL_DETAIL VARCHAR,
  CUSTOMER_FULL_DETAIL_EMBEDDING VECTOR(FLOAT, 768),
  CREATED_TIMESTAMP TIMESTAMP_NTZ,
  UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

create TABLE IF NOT EXISTS PUBLIC_SCHOOLS (
	X NUMBER(38,15),
	Y NUMBER(38,15),
	OBJECTID NUMBER(38,0),
	NCESID NUMBER(38,0),
	NAME VARCHAR(16777216),
	ADDRESS VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP NUMBER(38,0),
	ZIP4 VARCHAR(16777216),
	TELEPHONE VARCHAR(16777216),
	TYPE NUMBER(38,0),
	STATUS NUMBER(38,0),
	POPULATION NUMBER(38,0),
	COUNTY VARCHAR(16777216),
	COUNTYFIPS NUMBER(38,0),
	COUNTRY VARCHAR(16777216),
	LATITUDE NUMBER(38,13),
	LONGITUDE NUMBER(38,13),
	NAICS_CODE NUMBER(38,0),
	NAICS_DESC VARCHAR(16777216),
	SOURCE VARCHAR(16777216),
	SOURCEDATE TIMESTAMP_NTZ(9),
	VAL_METHOD VARCHAR(16777216),
	VAL_DATE TIMESTAMP_NTZ(9),
	WEBSITE VARCHAR(16777216),
	LEVEL_ VARCHAR(16777216),
	ENROLLMENT NUMBER(38,0),
	ST_GRADE VARCHAR(16777216),
	END_GRADE VARCHAR(16777216),
	DISTRICTID NUMBER(38,0),
	FT_TEACHER NUMBER(38,0),
	SHELTER_ID VARCHAR(16777216),
	CUSTOMER_FULL_DATA VARCHAR(16777216),
	CUSTOMER_FULL_DETAIL VARCHAR(16777216)
);