-- Consolidated setup for MDM Customer Matching
-- Includes: sequence/UDF, table DDLs, population, string full-detail, and embeddings

USE DATABASE MDM_CUSTOMER_MATCHING;
USE SCHEMA PUBLIC;  -- @Snowflake Docs

-- -----------------------------------------------------------------------------
-- Sequence and UDF for CUSTOMER_BUSINESS_ID
-- -----------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS CUSTOMER_BUSINESS_ID_SEQ
  START = 1
  INCREMENT = 1
  COMMENT = 'Sequence to generate the numeric component for CUSTOMER_BUSINESS_ID';

CREATE OR REPLACE FUNCTION GENERATE_CUSTOMER_BUSINESS_ID(SEQ_VALUE NUMBER)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Generates ID as CUS + 9-digit zero-padded number + Base36 check char.'
AS
$$
  'CUS'
  || LPAD(TO_VARCHAR(SEQ_VALUE), 9, '0')
  || IFF(MOD(SEQ_VALUE, 36) < 10,
         TO_VARCHAR(MOD(SEQ_VALUE, 36)),
         CHR(55 + MOD(SEQ_VALUE, 36))
     )
$$;

-- -----------------------------------------------------------------------------
-- Tables (with related post-creation updates grouped directly after each CREATE)
-- -----------------------------------------------------------------------------
-- CUSTOMER_ADDRESS (CTAS merges population + full detail + embedding)
CREATE OR REPLACE TABLE MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_ADDRESS AS
SELECT
  GENERATE_CUSTOMER_BUSINESS_ID(CUSTOMER_BUSINESS_ID_SEQ.NEXTVAL) AS CUSTOMER_BUSINESS_ID,
  v.NAME AS CUSTOMER_NAME,
  v.ADDRESS_LINE_1,
  v.ADDRESS_LINE_2,
  v.CITY,
  NULL AS COUNTY,
  v.STATE,
  v.POSTAL_CODE,
  NULL AS POSTALCODE_EXTENSION,
  v.COUNTRY,
  NULL AS PHONE,
  RTRIM(
    ARRAY_TO_STRING(
      ARRAY_CONSTRUCT_COMPACT(
        IFF(TRIM(v.NAME) = '', NULL, TRIM(v.NAME)),
        IFF(TRIM(v.ADDRESS_LINE_1) = '', NULL, TRIM(v.ADDRESS_LINE_1)),
        IFF(TRIM(v.ADDRESS_LINE_2) = '', NULL, TRIM(v.ADDRESS_LINE_2)),
        IFF(TRIM(v.CITY) = '', NULL, TRIM(v.CITY)),
        IFF(TRIM(v.STATE) = '', NULL, TRIM(v.STATE)),
        IFF(TRIM(v.POSTAL_CODE) = '', NULL, TRIM(v.POSTAL_CODE))
      ),
      ', '
    )
  ) AS CUSTOMER_FULL_DETAIL,
  AI_EMBED('snowflake-arctic-embed-m', customer_full_detail) AS CUSTOMER_FULL_DETAIL_EMBEDDING
FROM VALID_CUSTOMERS v;

-- CUSTOMER_IDENTIFIER (schema only; populated by tools/processes)
CREATE TABLE IF NOT EXISTS MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_IDENTIFIER (
  IDENTIFIER_TYPE VARCHAR,
  IDENTIFIER_VALUE VARCHAR,
  CUSTOMER_BUSINESS_ID VARCHAR,
  CUSTOMER_NAME VARCHAR,
  ADDRESS_ROLE VARCHAR,
  ADDRESS_LINE_1 VARCHAR,
  ADDRESS_LINE_2 VARCHAR,
  CITY VARCHAR,
  COUNTY VARCHAR,
  STATE VARCHAR,
  POSTAL_CODE VARCHAR,
  POSTALCODE_EXTENSION VARCHAR,
  COUNTRY VARCHAR,
  PHONE VARCHAR,
  VERIFICATION_STATUS_CODE VARCHAR,
  VERIFICATION_MESSAGE VARIANT,
  ENRICHED_INDICATOR VARCHAR,
  CONFIDENCE_SCORE FLOAT,
  CUSTOMER_FULL_DETAIL VARCHAR,
  CUSTOMER_FULL_DETAIL_EMBEDDING VECTOR(FLOAT, 768),
  CREATED_TIMESTAMP TIMESTAMP_NTZ,
  UPDATED_TIMESTAMP TIMESTAMP_NTZ
);

-- Run Python generate_customer_identifiers.py to populate CUSTOMER_IDENTIFIER


-- Build CUSTOMER_FULL_DETAIL for CUSTOMER_IDENTIFIER (skip NULL/blank parts)
UPDATE MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_IDENTIFIER ci
SET CUSTOMER_FULL_DETAIL = RTRIM(
  ARRAY_TO_STRING(
    ARRAY_CONSTRUCT_COMPACT(
      IFF(TRIM(ci.CUSTOMER_NAME) = '', NULL, TRIM(ci.CUSTOMER_NAME)),
      IFF(TRIM(ci.ADDRESS_LINE_1) = '', NULL, TRIM(ci.ADDRESS_LINE_1)),
      IFF(TRIM(ci.ADDRESS_LINE_2) = '', NULL, TRIM(ci.ADDRESS_LINE_2)),
      IFF(TRIM(ci.CITY) = '', NULL, TRIM(ci.CITY)),
      IFF(TRIM(ci.STATE) = '', NULL, TRIM(ci.STATE)),
      IFF(TRIM(ci.POSTAL_CODE) = '', NULL, TRIM(ci.POSTAL_CODE))
    ),
    ', '
  )
)
WHERE ci.CUSTOMER_FULL_DETAIL IS NULL OR TRIM(ci.CUSTOMER_FULL_DETAIL) = '';

-- Populate embeddings for CUSTOMER_IDENTIFIER where missing
UPDATE MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_IDENTIFIER
SET CUSTOMER_FULL_DETAIL_EMBEDDING = AI_EMBED('snowflake-arctic-embed-m', CUSTOMER_FULL_DETAIL)
WHERE CUSTOMER_FULL_DETAIL_EMBEDDING IS NULL AND CUSTOMER_FULL_DETAIL IS NOT NULL;

UPDATE customer_identifier ci
SET
    confidence_score = vector_cosine_similarity(ca.customer_full_detail_embedding, ci.customer_full_detail_embedding)
FROM
    customer_address ca
WHERE
    ci.customer_business_id = ca.customer_business_id;

update MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_IDENTIFIER set enriched_indicator = (select case when confidence_score > .95 then 'VALID' else 'ERROR' end) WHERE CONFIDENCE_SCORE IS NOT NULL;



CREATE OR REPLACE CORTEX SEARCH SERVICE MDM_CUSTOMER_ADDRESS_SEARCH
  ON customer_address
  WAREHOUSE = compute_wh
  TARGET_LAG = '1 hour'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-m'
AS (
	SELECT
		CUSTOMER_FULL_DETAIL,CUSTOMER_BUSINESS_ID,CUSTOMER_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,COUNTY,STATE,POSTAL_CODE,POSTALCODE_EXTENSION,COUNTRY
	FROM "MDM_CUSTOMER_MATCHING"."PUBLIC"."CUSTOMER_ADDRESS"
);


CREATE OR REPLACE CORTEX SEARCH SERVICE MDM_CUSTOMER_NAME_LOOKUP
  ON CUSTOMER_NAME
  WAREHOUSE = compute_wh
  TARGET_LAG = '1 hour'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-m'
AS (
    SELECT
        CUSTOMER_NAME,STATE,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,COUNTY,POSTAL_CODE,POSTALCODE_EXTENSION,COUNTRY,CUSTOMER_BUSINESS_ID
    FROM "MDM_CUSTOMER_MATCHING"."PUBLIC"."CUSTOMER_ADDRESS"
);