USE DATABASE MDM_CUSTOMER_MATCHING; -- @Snowflake Docs
USE SCHEMA PUBLIC; -- @Snowflake Docs

-- Rebuild CUSTOMER_FULL_DETAIL for CUSTOMER_ADDRESS
UPDATE MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_ADDRESS a
SET CUSTOMER_FULL_DETAIL = RTRIM(
  ARRAY_TO_STRING(
    ARRAY_CONSTRUCT_COMPACT(
      IFF(TRIM(a.CUSTOMER_NAME) = '', NULL, TRIM(a.CUSTOMER_NAME)),
      IFF(TRIM(a.ADDRESS_LINE_1) = '', NULL, TRIM(a.ADDRESS_LINE_1)),
      IFF(TRIM(a.ADDRESS_LINE_2) = '', NULL, TRIM(a.ADDRESS_LINE_2)),
      IFF(TRIM(a.CITY) = '', NULL, TRIM(a.CITY)),
      IFF(TRIM(a.STATE) = '', NULL, TRIM(a.STATE)),
      IFF(TRIM(a.POSTAL_CODE) = '', NULL, TRIM(a.POSTAL_CODE))
    ),
    ', '
  )
);

-- Re-embed CUSTOMER_ADDRESS using canonical text
UPDATE MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_ADDRESS
SET CUSTOMER_FULL_DETAIL_EMBEDDING = AI_EMBED('snowflake-arctic-embed-m', CUSTOMER_FULL_DETAIL)
WHERE CUSTOMER_FULL_DETAIL IS NOT NULL;

-- Rebuild CUSTOMER_FULL_DETAIL for CUSTOMER_IDENTIFIER where missing or not comma formatted
UPDATE MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_IDENTIFIER ci
SET CUSTOMER_FULL_DETAIL = RTRIM(
  ARRAY_TO_STRING(
    ARRAY_CONSTRUCT_COMPACT(
      IFF(TRIM(ci.CUSTOMER_NAME) = '', NULL, TRIM(ci.CUSTOMER_NAME)),
      IFF(TRIM(ci.ADDRESS_LINE_1) = '', NULL, TRIM(ci.ADDRESS_LINE_1)),
      IFF(TRIM(ci.ADDRESS_LINE_2) = '', NULL, TRIM(ci.ADDRESS_LINE_2)),
      IFF(TRIM(ci.CITY) = '', NULL, TRIM(ci.CITY)),
      IFF(TRIM(ci.STATE) = '', NULL, TRIM(ci.STATE)),
      IFF(TRIM(ci.POSTAL_CODE) = '', NULL, TRIM(ci.POSTAL_CODE))
    ),
    ', '
  )
)
WHERE ci.CUSTOMER_FULL_DETAIL IS NULL
   OR TRIM(ci.CUSTOMER_FULL_DETAIL) = ''
   OR ci.CUSTOMER_FULL_DETAIL NOT LIKE '%,%';

-- Re-embed CUSTOMER_IDENTIFIER using canonical text
UPDATE MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_IDENTIFIER
SET CUSTOMER_FULL_DETAIL_EMBEDDING = AI_EMBED('snowflake-arctic-embed-m', CUSTOMER_FULL_DETAIL)
WHERE CUSTOMER_FULL_DETAIL IS NOT NULL;

-- Recompute confidence scores where both embeddings exist
UPDATE MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_IDENTIFIER ci
SET confidence_score = VECTOR_COSINE_SIMILARITY(ca.customer_full_detail_embedding, ci.customer_full_detail_embedding)
FROM MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_ADDRESS ca
WHERE ci.customer_business_id = ca.customer_business_id
  AND ci.customer_full_detail_embedding IS NOT NULL
  AND ca.customer_full_detail_embedding IS NOT NULL;

-- Set enriched_indicator based on confidence_score
UPDATE MDM_CUSTOMER_MATCHING.PUBLIC.CUSTOMER_IDENTIFIER
SET enriched_indicator = (CASE WHEN confidence_score > 0.95 THEN 'VALID' ELSE 'ERROR' END)
WHERE confidence_score IS NOT NULL;


-- Rebuild CUSTOMER_FULL_DETAIL for TEST_MATCHES where missing or not comma formatted -- @Snowflake Docs
UPDATE TEST_MATCHES t
SET CUSTOMER_FULL_DETAIL = RTRIM(
  ARRAY_TO_STRING(
    ARRAY_CONSTRUCT_COMPACT(
      IFF(TRIM(t.NAME) = '', NULL, TRIM(t.NAME)),
      IFF(TRIM(t.ADDRESS_LINE_1) = '', NULL, TRIM(t.ADDRESS_LINE_1)),
      IFF(TRIM(t.ADDRESS_LINE_2) = '', NULL, TRIM(t.ADDRESS_LINE_2)),
      IFF(TRIM(t.CITY) = '', NULL, TRIM(t.CITY)),
      IFF(TRIM(t.STATE) = '', NULL, TRIM(t.STATE)),
      IFF(TRIM(t.POSTAL_CODE) = '', NULL, TRIM(t.POSTAL_CODE)),
      IFF(TRIM(t.COUNTRY) = '', NULL, TRIM(t.COUNTRY))
    ),
    ', '
  )
)
WHERE t.CUSTOMER_FULL_DETAIL IS NULL
   OR TRIM(t.CUSTOMER_FULL_DETAIL) = ''
   OR t.CUSTOMER_FULL_DETAIL NOT LIKE '%,%';

-- Rebuild CUSTOMER_FULL_DETAIL for VALID_CUSTOMERS where missing or not comma formatted -- @Snowflake Docs
UPDATE VALID_CUSTOMERS v
SET CUSTOMER_FULL_DETAIL = RTRIM(
  ARRAY_TO_STRING(
    ARRAY_CONSTRUCT_COMPACT(
      IFF(TRIM(v.NAME) = '', NULL, TRIM(v.NAME)),
      IFF(TRIM(v.ADDRESS_LINE_1) = '', NULL, TRIM(v.ADDRESS_LINE_1)),
      IFF(TRIM(v.ADDRESS_LINE_2) = '', NULL, TRIM(v.ADDRESS_LINE_2)),
      IFF(TRIM(v.CITY) = '', NULL, TRIM(v.CITY)),
      IFF(TRIM(v.STATE) = '', NULL, TRIM(v.STATE)),
      IFF(TRIM(v.POSTAL_CODE) = '', NULL, TRIM(v.POSTAL_CODE)),
      IFF(TRIM(v.COUNTRY) = '', NULL, TRIM(v.COUNTRY))
    ),
    ', '
  )
)
WHERE v.CUSTOMER_FULL_DETAIL IS NULL
   OR TRIM(v.CUSTOMER_FULL_DETAIL) = ''
   OR v.CUSTOMER_FULL_DETAIL NOT LIKE '%,%';
-- Re-embed TEST_MATCHES and VALID_CUSTOMERS to align models
UPDATE TEST_MATCHES
SET CUSTOMER_FULL_DETAIL_EMBEDDING = AI_EMBED('snowflake-arctic-embed-m', CUSTOMER_FULL_DETAIL)
WHERE CUSTOMER_FULL_DETAIL IS NOT NULL;

UPDATE VALID_CUSTOMERS
SET CUSTOMER_FULL_DETAIL_EMBEDDING_VECTOR = AI_EMBED('snowflake-arctic-embed-m', CUSTOMER_FULL_DETAIL)
WHERE CUSTOMER_FULL_DETAIL IS NOT NULL;

